/* ============================================
   Yoma - canonical Gemara knowledge schema
   ============================================
   LEARNING_SCHEMA_MAP is the canonical schema reference for the Gemara
   knowledge layer stored in learning_data.js (generated by
   scripts/build_learning_data.py). It serves as the contract for all
   consumers: app display, image generation, tutoring, quizzes, flashcards,
   search, semantic navigation, learning paths, audio, future API, and
   future masechtot.

   This file is a plain script - no import/export - and is NOT loaded by the
   browser. It is the human and agent reference for what belongs in the
   schema and what does not. Validation is enforced by scripts/validate_*.py.

   FIELD STATUS MARKERS
   --------------------
   canonical     - Core Gemara knowledge. Store and maintain. Every consumer
                   may read this; no consumer should replace it with its own
                   analysis.
   optional      - Use when relevant; leave as empty string/array when not
                   applicable. Do not fabricate content to fill optional fields.
   derived       - Can be recomputed or generated from canonical data. Store
                   only when a consumer needs it pre-materialized (e.g. image
                   filenames written after the asset is created). Do not
                   manually maintain unless the derivation is expensive.
   helper        - Editorial aid (translations, notes). Not source-validated.
                   Always stamped with enSource / confidence fields.
   never_stored  - Belongs in the consumer, not in learning_data.js. Includes:
                   rendered image prompts, one-off UI state, temporary rendering
                   decisions, output-format-specific descriptions, and anything
                   that describes how to present the sugya rather than what the
                   sugya contains.

   INTERPRETATION POLICY
   ---------------------
   Each sugya has one primary learning angle: the framing that best helps a
   learner understand the sugya's main move. Store it in display.whats and
   the learning.* fields. Use alternateAngles only when a sugya genuinely has
   more than one strong educational framing that would benefit materially
   different learners. Do not add alternateAngles to be comprehensive.

   IMAGE GENERATION POLICY
   -----------------------
   Image prompts must be generated from the canonical knowledge fields in this
   schema (argumentFlow, visualizableElements, learning, concepts) rather than
   from a separate editorial layer or invented analysis. The image is a
   rendering of what is already in the schema. Never store image prompts or
   image-specific descriptions inside learning_data.js.

   Each field entry uses:
     { type, status, required, purpose, notes }
   ============================================ */

const LEARNING_SCHEMA_MAP = {

  // ---- version + provenance globals (top of learning_data.js) ----
  versions: {
    DATA_VERSION: {
      type: "string",
      status: "canonical",
      required: true,
      purpose: "Single canonical app/data version (e.g. \"10.51\").",
      notes: "Edited only in learning_data.js; pre-commit sync_version.py mirrors it to VERSION, package.json, index.html cache-busters. App reads it as a global."
    },
    DATA_SCHEMA_VERSION: {
      type: "string",
      status: "canonical",
      required: true,
      purpose: "Version of the sugya/line object shape itself.",
      notes: "Bump ONLY when the object shape changes, independently of DATA_VERSION."
    },
    LEARNING_DATA_VERSION: {
      type: "string",
      status: "derived",
      required: true,
      purpose: "Alias of DATA_VERSION for learning-layer consumers.",
      notes: "Currently set equal to DATA_VERSION by the generator. Kept for consumers that distinguish app version from learning version."
    }
  },

  // ---- TRACTATE_META global ----
  tractateMeta: {
    id:              { type: "string",    status: "canonical", required: true,  purpose: "Tractate slug, e.g. \"yoma\".", notes: "" },
    title:           { type: "string",    status: "canonical", required: true,  purpose: "English tractate title.", notes: "" },
    title_he:        { type: "string",    status: "canonical", required: true,  purpose: "Hebrew tractate title with nikud.", notes: "" },
    seder:           { type: "string",    status: "canonical", required: true,  purpose: "Order of the Mishnah, e.g. \"Moed\".", notes: "" },
    schemaVersion:   { type: "string",    status: "derived",   required: true,  purpose: "Mirror of DATA_SCHEMA_VERSION.", notes: "" },
    dataVersion:     { type: "string",    status: "derived",   required: true,  purpose: "Mirror of DATA_VERSION.", notes: "" },
    sourceEdition:   { type: "string",    status: "canonical", required: true,  purpose: "Human-readable source provenance.", notes: "e.g. \"Vilna / Sefaria / talmud.dev\"." },
    dafRange:        { type: "object",    status: "canonical", required: true,  purpose: "{ first, last } daf covered.", notes: "" },
    totalDaf:        { type: "number",    status: "canonical", required: true,  purpose: "Count of daf entries.", notes: "" },
    fullyStructured: { type: "string[]",  status: "derived",   required: true,  purpose: "Daf ids that carry the full learning + rashi layer.", notes: "Mirrors ENRICHED in build_learning_data.py. Maintained by the generator; do not edit by hand." }
  },

  // ---- one entry of DAF_CONTENT, keyed by daf id ("2a") ----
  daf: {
    canonicalRef: { type: "string",      status: "canonical", required: true,  purpose: "Sefaria daf ref, e.g. \"Yoma 2a\".", notes: "Enriched daf only." },
    daf:          { type: "string",      status: "canonical", required: true,  purpose: "Daf id, e.g. \"2a\".", notes: "" },
    summary:      { type: "string",      status: "canonical", required: true,  purpose: "One-paragraph overview of the page.", notes: "Modern Orthodox editorial English. See CLAUDE.md for editorial voice guidelines." },
    sugyot:       { type: "sugya[]",     status: "canonical", required: true,  purpose: "Ordered sugyot on the daf.", notes: "See sugya below." },
    glossary:     { type: "object[]",    status: "optional",  required: false, purpose: "Key-term cards for the daf.", notes: "Each: { he, translit, en }. Terms that recur across sugyot or are essential to the daf's argument." },
    rashiLines:   { type: "rashiLine[]", status: "helper",    required: false, purpose: "Daf-level Rashi helper layer.", notes: "Enriched daf only. See rashiLine below. NOT part of Gemara source validation." },
    review:       { type: "object",      status: "optional",  required: false, purpose: "Editorial review/status metadata.", notes: "{ status: controlledValues.reviewStatus }." }
  },

  // ---- one Gemara line object inside a sugya's lines: [] array ----
  // STRICT source layer: he/en are Sefaria-validated and gated by
  // validate_sefaria.py, validate_en.py, order_audit.py.
  line: {
    id:           { type: "string",  status: "canonical", required: true,  purpose: "Stable line id, e.g. \"yoma-002a-l01\".", notes: "Pattern: yoma-<pad daf>-l<vilna_line>. Letter suffix (l01a, l01b) when two lines share the same Vilna line number." },
    kind:         { type: "string",  status: "canonical", required: true,  purpose: "Line type (controlledValues.lineKind).", notes: "mishna | gemara | aside | baraita | tosefta" },
    he:           { type: "string",  status: "canonical", required: true,  purpose: "Verbatim Sefaria Hebrew for the segment.", notes: "VALIDATED. Character-for-character from Sefaria; may contain \\n for Vilna line breaks." },
    vilna_line:   { type: "number",  status: "canonical", required: true,  purpose: "Starting Vilna column line number.", notes: "Must sit on a separate physical line from he: (order_audit pairs them)." },
    en:           { type: "string",  status: "canonical", required: false, purpose: "Verbatim Sefaria English for the same segment index.", notes: "VALIDATED by validate_en.py against the same Sefaria index as he." },
    sefaria_ref:  { type: "string",  status: "canonical", required: false, purpose: "Sefaria segment ref, e.g. \"Yoma.2a.1\".", notes: "" },
    commentaries: { type: "object",  status: "optional",  required: false, purpose: "Per-line commentary hooks: { rashi: [], tosafot: [] }.", notes: "Currently empty placeholders; daf-level rashiLines carries the active Rashi layer." }
  },

  // ---- one sugya object inside daf.sugyot ----
  sugya: {
    id:           { type: "string",    status: "canonical", required: true,  purpose: "Stable sugya id, e.g. \"yoma-002a-s01\".", notes: "Pattern: yoma-<pad daf>-s<2-digit number>." },
    canonicalRef: { type: "string",    status: "canonical", required: false, purpose: "Sefaria daf ref, e.g. \"Yoma 2a\".", notes: "Inherited from the parent daf entry." },
    daf:          { type: "string",    status: "canonical", required: true,  purpose: "Owning daf id.", notes: "" },
    sugyaNumber:  { type: "number",    status: "canonical", required: true,  purpose: "1-based order within the daf.", notes: "" },
    lineRange:    { type: "object",    status: "canonical", required: true,  purpose: "{ startLineId, endLineId, startVilnaLine, endVilnaLine }.", notes: "startLineId/endLineId use the actual computed line ids (which may have letter suffixes for duplicates)." },
    display:      { type: "object",    status: "canonical", required: false, purpose: "Reader-facing summary fields.", notes: "See display sub-schema below." },
    learning:     { type: "object",    status: "canonical", required: false, purpose: "Primary educational analysis of the sugya.", notes: "See learning sub-schema below. One angle per sugya; see Interpretation Policy above." },
    lines:        { type: "line[]",    status: "canonical", required: true,  purpose: "Ordered Gemara lines (the STRICT source layer).", notes: "See line above." },
    argumentFlow: { type: "object[]",  status: "canonical", required: false, purpose: "Typed reasoning steps tracing the Gemara's argument.", notes: "See argumentFlow sub-schema below." },
    concepts:     { type: "object",    status: "canonical", required: false, purpose: "Structured knowledge entities referenced by the sugya.", notes: "Shape: { people?, places?, objects?, halacha?, reasoning?, keyTerms? }. keyTerms is a flat string array for quick display; the others group entity ids by category." },
    conceptRefs:  { type: "string[]",  status: "optional",  required: false, purpose: "Ids into a shared cross-tractate concept store.", notes: "Not yet populated. Reserved for future semantic navigation." },
    requiresUnderstanding: { type: "string[]", status: "optional", required: false, purpose: "Sugya ids that should be understood before this one.", notes: "Used for learning path ordering and tutor context." },
    topicTags:    { type: "string[]",  status: "canonical", required: false, purpose: "Normalized ASCII topic slugs for search and filtering.", notes: "4-6 slugs per sugya, lowercase, hyphen-separated (e.g. 'gezera-shavah', 'kohen-gadol'). Used by search, learning-path grouping, and semantic navigation." },
    misconceptions:  { type: "object[]", status: "optional", required: false, purpose: "Common errors + corrections.", notes: "Each: { misconception, correction, correctedByStepId? }. Use only when a specific documented misunderstanding exists." },
    relatedSugyot:   { type: "string[]", status: "optional", required: false, purpose: "Ids of related sugyot elsewhere in the tractate.", notes: "For semantic navigation and 'see also' features." },
    visualizableElements: { type: "object[]", status: "canonical", required: false, purpose: "Reusable knowledge elements in the sugya that can power images, tutoring, quizzes, audio, or navigation.", notes: "See visualizableElements sub-schema below. NOT an image-specific field." },
    quizSeeds:    { type: "object[]",  status: "optional",  required: false, purpose: "Seed prompts for quiz generation.", notes: "Each: { question, answer, sourceRefs? }. Include 2 per sugya at different difficulty levels when possible." },
    finalRuling:  { type: "string",    status: "optional",  required: false, purpose: "Halachic bottom line, if the sugya reaches one.", notes: "Leave empty for sugyot that are purely analytical or end unresolved." },
    difficulty:   { type: "string",    status: "optional",  required: false, purpose: "Intended learner level (controlledValues.difficulty).", notes: "intro | intermediate | advanced." },
    alternateAngles: { type: "object[]", status: "optional", required: false, purpose: "Alternative educational framings when multiple strong angles exist.", notes: "Use sparingly. See Interpretation Policy above." },
    review:       { type: "object",    status: "optional",  required: false, purpose: "Editorial review/status metadata.", notes: "{ status: controlledValues.reviewStatus }." },
    image:        { type: "string",    status: "derived",   required: false, purpose: "Infographic .webp filename, set after the asset is created.", notes: "Lives in assets/generated-images/. Generated from canonical knowledge fields; do not add before the asset exists." },
    image_alt:    { type: "string",    status: "derived",   required: false, purpose: "Alt text for the infographic.", notes: "Written when image is wired in." }
  },

  // ---- display sub-schema (sugya.display) ----
  // Reader-facing summary. All fields are editorial English.
  display: {
    title:        { type: "string", status: "canonical", required: true,  purpose: "Short heading for the sugya.", notes: "" },
    oneLine:      { type: "string", status: "canonical", required: false, purpose: "One-sentence summary suitable for a card or tooltip.", notes: "" },
    shortSummary: { type: "string", status: "optional",  required: false, purpose: "2-3 sentence summary for search results or preview panels.", notes: "" },
    whats:        { type: "string", status: "canonical", required: false, purpose: "Full editorial explanation of the sugya's argument.", notes: "The primary learning angle. Modern Orthodox editorial English." },
    hint:         { type: "string", status: "canonical", required: false, purpose: "A guiding question to hold in mind while reading.", notes: "Often points at the coreTension or the coreMove." }
  },

  // ---- learning sub-schema (sugya.learning) ----
  // The primary educational analysis. One angle per sugya (see Interpretation Policy).
  // All fields are canonical knowledge about the sugya itself - not output-specific.
  learning: {
    learnerQuestion:  { type: "string", status: "canonical", required: true,  purpose: "The question a learner naturally asks when first encountering this sugya.", notes: "Drives tutoring sessions, quiz framing, and audio introductions." },
    coreTension:      { type: "string", status: "canonical", required: true,  purpose: "The central legal or logical problem the sugya is resolving.", notes: "The 'what's at stake' - distinct from the resolution." },
    coreMove:         { type: "string", status: "canonical", required: true,  purpose: "The key analytical move the Gemara makes to advance the argument.", notes: "Often the turning point that resolves the coreTension. Suitable for flash cards." },
    resolution:       { type: "string", status: "canonical", required: false, purpose: "How the sugya settles the coreTension.", notes: "May be partial or deferred. Leave empty if the sugya closes unresolved." },
    takeaway:         { type: "object", status: "canonical", required: true,  purpose: "The durable learning principle extracted from the sugya.", notes: "Shape: { type (controlledValues.takeawayType), text }." },
    ahaMoment:        { type: "string", status: "canonical", required: true,  purpose: "The surprising or counterintuitive insight that makes this sugya memorable.", notes: "Suitable for audio hooks and tutor 'reveal' moments. Focus on what surprises even an experienced learner." },
    learningBlocker:  { type: "string", status: "canonical", required: true,  purpose: "The most common misunderstanding a learner brings to this sugya.", notes: "Useful for tutoring, error-catching flashcards, and common-mistake quizzes." },
    memoryAnchor:     { type: "string", status: "canonical", required: true,  purpose: "A short vivid hook - image, phrase, or contrast - that anchors the sugya's main move in memory.", notes: "Different from ahaMoment: ahaMoment is the insight; memoryAnchor is the mnemonic for retaining it. One or two sentences maximum." },
    reasoningPattern: { type: "object", status: "optional",  required: false, purpose: "The named logical pattern the sugya exemplifies.", notes: "Shape: { id, category (logical|hermeneutical|conceptual), notes }. Used by semantic navigation, learning paths, and cross-sugya analysis." }
  },

  // ---- argumentFlow sub-schema (sugya.argumentFlow[]) ----
  // Typed steps tracing the Gemara's argument structure.
  // Consumers: tutoring (step-by-step walkthrough), audio (narration order),
  // image generation (scene selection), learning paths (argument pattern recognition).
  argumentFlow: {
    id:         { type: "string", status: "canonical", required: true,  purpose: "Stable step id, e.g. \"step-01\".", notes: "" },
    type:       { type: "string", status: "canonical", required: true,  purpose: "Step type (controlledValues.argumentStepType).", notes: "See controlled values for the full list and semantics." },
    label:      { type: "string", status: "canonical", required: true,  purpose: "Short heading for the step, e.g. \"Rabbi Yehuda extends the logic\".", notes: "" },
    speaker:    { type: "string", status: "canonical", required: false, purpose: "Who makes this move: a named Sage, 'Gemara', 'Mishnah', etc.", notes: "Use the most specific attribution the text supports." },
    text:       { type: "string", status: "canonical", required: true,  purpose: "Editorial paraphrase of the step's content.", notes: "Modern Orthodox editorial English. Not verbatim Gemara - a clear paraphrase of the move." },
    sourceRefs: { type: "object[]", status: "optional", required: false, purpose: "Links to source line ids for this step.", notes: "Each: { sourceType, lineId, vilnaLine, note }. Used by tutoring to anchor steps to specific Gemara lines." }
  },

  // ---- visualizableElements sub-schema (sugya.visualizableElements[]) ----
  // Generic registry of reusable knowledge elements identified in the sugya.
  // NOT an image-specific field. May power images, tutoring diagrams, quizzes,
  // audio descriptions, search, and semantic navigation equally.
  // Element categories: person, object, place, action, text, timeline,
  //   relationship, contrast, sequence.
  visualizableElements: {
    item:     { type: "string", status: "canonical", required: true,  purpose: "Description of the element.", notes: "E.g. 'The Parhedrin chamber with KG isolated from his household', 'The kal va-chomer from less to more sanctified'." },
    role:     { type: "string", status: "canonical", required: true,  purpose: "How this element functions in the sugya's argument or pedagogy.", notes: "E.g. 'anchor' (central scene), 'aha' (reveals the insight), 'contrast' (shows the dispute visually), 'sequence' (timeline of steps)." },
    priority: { type: "number", status: "optional",  required: false, purpose: "Relative importance for visualization (1 = most important).", notes: "" }
  },

  // ---- one Rashi helper line inside daf.rashiLines ----
  // HELPER layer: he is source text; en is an editorial helper translation and
  // is NOT Sefaria-validated. Kept entirely separate from the Gemara source
  // layer (line.he / line.en) and from Gemara validation.
  rashiLine: {
    id:          { type: "string",   status: "canonical", required: true,  purpose: "Stable Rashi line id, e.g. \"rashi-yoma-002a-001\".", notes: "Pattern: rashi-yoma-<pad daf>-<3-digit vilna line>." },
    sourceType:  { type: "string",   status: "canonical", required: true,  purpose: "Always \"rashi\" here.", notes: "controlledValues.commentarySourceType." },
    daf:         { type: "string",   status: "canonical", required: true,  purpose: "Owning daf id, e.g. \"2a\".", notes: "" },
    vilnaLine:   { type: "number",   status: "canonical", required: true,  purpose: "1-based Vilna Rashi-column line number.", notes: "Order/count must match the talmud.dev rashi[] source." },
    he:          { type: "string",   status: "canonical", required: true,  purpose: "Verbatim Rashi Hebrew (Vilna order, unvowelized).", notes: "SOURCE: talmud.dev rashi[] ONLY. Never fabricated, never from Sefaria." },
    en:          { type: "string",   status: "helper",    required: false, purpose: "Helper English translation of the line.", notes: "Editorial helper - NOT source-validated. Present whenever he is present." },
    enSource:    { type: "string",   status: "helper",    required: true,  purpose: "Provenance of en (controlledValues.enSource).", notes: "\"ai_helper_translation\" unless replaced by a validated source." },
    source:      { type: "string",   status: "canonical", required: true,  purpose: "Provenance of he.", notes: "\"talmud.dev\"." },
    confidence:  { type: "string",   status: "helper",    required: true,  purpose: "Trust level (controlledValues.confidence).", notes: "\"helper\" for the editorial English layer." },
    linkedGemaraLineIds: { type: "string[]", status: "optional", required: false, purpose: "Gemara line ids this Rashi comment addresses.", notes: "Best-effort by dibur hamatchil. Usable by tutor/image/learning tools for context." }
  },

  // ---- shape of a Sefaria-style source reference string ----
  sourceRef: {
    pattern: {
      type: "string",
      status: "canonical",
      required: false,
      purpose: "Sefaria ref, \"<Book>.<Daf>.<Segment>\" (e.g. \"Yoma.2a.1\").",
      notes: "Used in line.sefaria_ref. Tanakh refs inside en are auto-linked by app.jsx."
    }
  },

  // ---- enumerated values used across the shapes above ----
  controlledValues: {
    lineKind: ["mishna", "gemara", "aside", "baraita", "tosefta"],

    // Argument step types - the semantics of each:
    //   case             - Presents the base situation or rule being analyzed
    //   question         - Raises a problem or asks for a source
    //   proposal         - Suggests a candidate rule, source, or interpretation
    //   challenge        - Attacks a prior step (stronger than an objection)
    //   objection        - Raises a difficulty without fully attacking
    //   counter_objection - Rebuts a challenge or objection
    //   proof            - Brings a supporting source or inference
    //   answer           - Responds to a question or objection
    //   distinction      - Differentiates two cases the argument conflated
    //   rejection        - Definitively dismisses a proposal
    //   resolution       - Settles the coreTension
    //   takeaway         - Draws the durable principle from the argument
    argumentStepType: [
      "case", "question", "proposal", "challenge", "objection",
      "counter_objection", "proof", "answer", "distinction",
      "qualification", "rejection", "resolution", "takeaway"
    ],

    // takeaway.type - the kind of principle the sugya yields:
    takeawayType: [
      "logical_principle", "derivation_principle", "legal_principle",
      "conceptual", "open_question"
    ],

    difficulty: ["intro", "intermediate", "advanced"],
    reviewStatus: ["draft", "in-review", "verified"],
    commentarySourceType: ["rashi", "tosafot"],
    enSource: ["ai_helper_translation", "sefaria_validated", "editorial"],
    confidence: ["helper", "validated"]
  }
};

/* CommonJS export for Node tooling; harmless as a plain browser script. */
if (typeof module !== "undefined" && module.exports) {
  module.exports = { LEARNING_SCHEMA_MAP };
}
