#!/usr/bin/env python3
"""
generate_module_docs.py - generic (--module/--search-root) module status
doc generator (Phase 3 six-row closure campaign, row 29: fixture
documentation generation succeeds).

Unlike modules/yoma/scripts/generate_rashi_docs.py (PER_MODULE tier: reads
Yoma's own scaffold-debt baseline and task-type map to regenerate the
Rashi audit backlog narrative), this derives a small, fully deterministic
status doc for any resolvable module - real or fixture - purely from:

  - the resolved module descriptor (identity, dafRange, totalDaf,
    capabilities, sourceAcquisition strategy)
  - coverage.json (module.json's declared paths.coverageFile)
  - the corpus counts in learning_data.js, read via
    scripts/validate_module_schema.mjs (the generic JS-object-literal
    reader already built for Step 9A) rather than a second bespoke parser

Deliberately excludes every volatile field - no commit hash, no
timestamp, and no live VERSION stamp either (VERSION bumps on nearly
every PR in this campaign; a module whose own content has not changed
should not go stale just because an unrelated PR bumped the platform
version - the exact false-alarm class Step 7 found with a commit-hash-
stamped doc, extended here to VERSION too). The output is therefore
byte-reproducible from committed inputs alone, so --check is a plain
string comparison.

Usage:
  python3 scripts/generate_module_docs.py --module yoma
  python3 scripts/generate_module_docs.py --module demotractate --search-root tests/fixtures/modules
  python3 scripts/generate_module_docs.py --module demotractate --search-root tests/fixtures/modules --check
  python3 scripts/generate_module_docs.py --module yoma --out /tmp/scratch.md   # dry run, writes nowhere in the repo
"""
import argparse
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).parent.parent

sys.path.insert(0, str(Path(__file__).parent))
import module_resolver  # noqa: E402

VALIDATOR = REPO / "scripts" / "validate_module_schema.mjs"

COUNTS_RE = re.compile(r"Daf:\s*(\d+)\s+Sugyot:\s*(\d+)\s+ArgumentFlow steps:\s*(\d+)")
RASHI_RE = re.compile(r"capabilities\.rashi\.enabled=(true|false) rashiLines=(\d+)")
LITERAL_RE = re.compile(r"capabilities\.literalTranslation\.enabled=(true|false) en_lit fields=(\d+)")


def physical_root(key, search_root):
    if search_root:
        return Path(search_root) / key
    return REPO / "modules" / key


def load_corpus_counts(key, search_root):
    """Run the generic capability-aware validator and parse its printed
    counts, rather than re-parsing learning_data.js's JS-object-literal
    syntax a second time in Python. A module that fails validation cannot
    be documented - the doc describes a valid module's state."""
    cmd = ["node", str(VALIDATOR), "--module", key]
    if search_root:
        cmd += ["--search-root", str(search_root)]
    result = subprocess.run(cmd, cwd=REPO, capture_output=True, text=True)
    if result.returncode != 0:
        sys.exit(f"ERROR: module {key!r} does not pass validate_module_schema.mjs; "
                  f"cannot generate docs for an invalid module:\n{result.stderr}")
    out = result.stdout
    counts_m = COUNTS_RE.search(out)
    rashi_m = RASHI_RE.search(out)
    literal_m = LITERAL_RE.search(out)
    if not (counts_m and rashi_m and literal_m):
        sys.exit(f"ERROR: could not parse validate_module_schema.mjs output for {key!r}:\n{out}")
    return {
        "daf": int(counts_m.group(1)),
        "sugyot": int(counts_m.group(2)),
        "argument_flow_steps": int(counts_m.group(3)),
        "rashi_enabled": rashi_m.group(1) == "true",
        "rashi_lines": int(rashi_m.group(2)),
        "literal_enabled": literal_m.group(1) == "true",
        "en_lit_fields": int(literal_m.group(2)),
    }


def load_coverage(descriptor, key, search_root):
    root = physical_root(key, search_root)
    logical_root = descriptor["paths"]["root"]
    logical_coverage = descriptor["paths"]["coverageFile"]
    suffix = logical_coverage[len(logical_root):].lstrip("/")
    coverage_path = root / suffix
    if not coverage_path.is_file():
        sys.exit(f"ERROR: coverage file not found at {coverage_path}")
    import json
    return json.loads(coverage_path.read_text())


def render_doc(key, descriptor, counts, coverage):
    d = descriptor.to_dict()
    caps = d["capabilities"]
    sa = caps["sourceAcquisition"]
    daf_range = d.get("dafRange") or {}

    lines = [
        f"# Module status: {key}",
        "",
        f"Generated by `scripts/generate_module_docs.py` - regenerate with "
        f"`python3 scripts/generate_module_docs.py --module {key}"
        + (" --search-root <path>" if key != "yoma" else "") + "`. "
        "Do not hand-edit.",
        "",
        f"- Display name: {d['displayNameEn']}",
        f"- Status: {d['status']} (publishable: {str(d['publishable']).lower()})",
        f"- Daf range: {daf_range.get('first', '?')} - {daf_range.get('last', '?')} "
        f"({d['totalDaf']} total daf)",
        "",
        "## Corpus counts (from learning_data.js, via validate_module_schema.mjs)",
        "",
        f"- Daf: {counts['daf']}",
        f"- Sugyot: {counts['sugyot']}",
        f"- ArgumentFlow steps: {counts['argument_flow_steps']}",
        "",
        "## Coverage (from coverage.json)",
        "",
        f"- dafCompleted / dafTotal: {coverage.get('dafCompleted')} / {coverage.get('dafTotal')}",
        f"- sugyaCount: {coverage.get('sugyaCount')}",
        f"- rashiLineCount: {coverage.get('rashiLineCount')}",
        f"- enrichedDaf: {', '.join(coverage.get('enrichedDaf', []))}",
        "",
        "## Capabilities",
        "",
        f"- rashi: enabled={str(counts['rashi_enabled']).lower()}, "
        f"rashiLines in corpus={counts['rashi_lines']}",
        f"- literalTranslation: enabled={str(counts['literal_enabled']).lower()}, "
        f"en_lit fields in corpus={counts['en_lit_fields']}",
        f"- sourceAcquisition: {sa['strategy']}"
        + (f" (sourceSystem: {sa.get('sourceSystem')})" if sa['strategy'] == "remote-fetch" else
           f" (fixtureInputDir: {sa.get('fixtureInputDir')})"),
        "",
    ]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--module", required=True)
    ap.add_argument("--search-root", default=None)
    ap.add_argument("--out", default=None,
                     help="output path; defaults to docs/module-status-<module>.md")
    ap.add_argument("--check", action="store_true",
                     help="exit 1 if the committed doc differs from freshly generated content")
    opts = ap.parse_args()

    try:
        descriptor = module_resolver.resolve_module(opts.module, search_root=opts.search_root)
    except module_resolver.ModuleResolutionError as e:
        sys.exit(f"ERROR: cannot resolve module {opts.module!r}: {e}")

    counts = load_corpus_counts(opts.module, opts.search_root)
    coverage = load_coverage(descriptor, opts.module, opts.search_root)
    content = render_doc(opts.module, descriptor, counts, coverage)

    out_path = Path(opts.out) if opts.out else REPO / "docs" / f"module-status-{opts.module}.md"

    if opts.check:
        if not out_path.is_file():
            sys.exit(f"STALE: {out_path} does not exist. Run: "
                      f"python3 scripts/generate_module_docs.py --module {opts.module}"
                      + (f" --search-root {opts.search_root}" if opts.search_root else ""))
        current = out_path.read_text()
        if current != content:
            print(f"STALE: {out_path} does not match freshly generated content.")
            print(f"Run: python3 scripts/generate_module_docs.py --module {opts.module}"
                  + (f" --search-root {opts.search_root}" if opts.search_root else ""))
            sys.exit(1)
        print(f"OK: {out_path} is fresh.")
        return

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content)
    print(f"wrote {out_path} ({counts['daf']} daf, {counts['sugyot']} sugyot, "
          f"{counts['argument_flow_steps']} argumentFlow steps)")


if __name__ == "__main__":
    main()
