#!/usr/bin/env python3
"""
check_generated_freshness.py - verify that the committed generated outputs
(learning_data.js and coverage.json) are exactly what regeneration from the
enrichment JSON source plus literal-layer reinjection would produce.

Catches:
  - hand edits to the generated learning_data.js (forbidden by CLAUDE.md)
  - commits that changed *.learning.json or assets/literal_en/ without
    regenerating
  - non-deterministic or divergent generation

Method (safe for the working tree):
  1. Snapshot the current bytes of learning_data.js and coverage.json.
  2. Run build_learning_data.py, then build_literal_layer.py --apply
     (both write in place).
  3. Compare the regenerated bytes to the snapshot.
  4. ALWAYS restore the snapshot bytes before exiting, so the working tree is
     left exactly as found regardless of outcome.
  5. Exit 1 with a report if regeneration produced different bytes.

Offline, no network.
"""
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
SCRIPTS = Path(__file__).parent
TARGETS = [ROOT / "learning_data.js", ROOT / "coverage.json"]


def main():
    snapshots = {}
    for t in TARGETS:
        if not t.exists():
            sys.exit(f"ERROR: {t} not found; cannot check freshness.")
        snapshots[t] = t.read_bytes()

    try:
        for cmd in (
            [sys.executable, str(SCRIPTS / "build_learning_data.py")],
            [sys.executable, str(SCRIPTS / "build_literal_layer.py"), "--apply"],
        ):
            r = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
            if r.returncode != 0:
                print(r.stdout)
                print(r.stderr, file=sys.stderr)
                sys.exit(f"ERROR: regeneration step failed: {' '.join(cmd)}")

        stale = []
        for t in TARGETS:
            if t.read_bytes() != snapshots[t]:
                stale.append(t.name)
    finally:
        for t, data in snapshots.items():
            t.write_bytes(data)

    if stale:
        print("Generated-output freshness check FAILED:\n")
        for name in stale:
            print(f"  ERROR  {name} is not what regeneration produces "
                  f"(hand-edited, or sources changed without regenerating).")
        print("\nFix: run  python3 scripts/build_learning_data.py && "
              "python3 scripts/build_literal_layer.py --apply  from modules/yoma/ "
              "and commit the result. Never hand-edit generated files.")
        print("(Working tree was restored to its pre-check state.)")
        sys.exit(1)

    print("OK: learning_data.js and coverage.json are fresh "
          "(regeneration reproduces the committed bytes exactly; working tree untouched).")


if __name__ == "__main__":
    main()
