#!/usr/bin/env python3
"""
generate_sourcerefs_blocker_table.py - Step 2 deliverable for the 33
residual sourceRefs defects (Phase 2B of docs/platform-closure-plan.md).

Merges two inputs that are deliberately kept separate:

  docs/reports/data/sourcerefs-blocker-dossier.json
      mechanical evidence, produced by generate_sourcerefs_blocker_dossier.py.
      Regenerate that file first if the corpus has changed.

  docs/reports/sourcerefs-blocker-classifications.json
      the hand-authored judgment layer: one of the five blocker classes
      (QUALIFIED_CROSS_DAF / ABSENT_OR_UNANCHORED / TIED_CANDIDATES /
      REPAIRABLE_LOCAL / METADATA_ONLY) per case, with its evidence,
      proposed safe action and residual uncertainty. This file is read-only
      input to this script, not generated by it - the judgment calls it
      records came from reading full argumentFlow context and full source
      text for every case, which is not something a script derives.

Writes docs/reports/data/sourcerefs-blocker-table.json (machine-readable)
and docs/reports/sourcerefs-blocker-table.md (human-readable). Read-only
with respect to the corpus: no *.learning.json file is touched. Applying
any of the proposed actions is Step 4 of the current campaign, a separate,
later, bounded repair PR per blocker class.

Run: cd modules/yoma && python3 scripts/generate_sourcerefs_blocker_table.py
"""
import json
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).parent.parent
REPO = ROOT.parent.parent
DATA_DIR = REPO / "docs" / "reports" / "data"

VALID_CLASSES = {
    "QUALIFIED_CROSS_DAF", "ABSENT_OR_UNANCHORED", "TIED_CANDIDATES",
    "REPAIRABLE_LOCAL", "METADATA_ONLY",
}


def main():
    dossier_path = DATA_DIR / "sourcerefs-blocker-dossier.json"
    classifications_path = REPO / "docs" / "reports" / "sourcerefs-blocker-classifications.json"

    dossier = json.loads(dossier_path.read_text(encoding="utf-8"))
    classifications = json.loads(classifications_path.read_text(encoding="utf-8"))
    by_key = {(c["sugyaId"], c["stepId"]): c for c in classifications}

    missing = [
        f"{e['sugyaId']}/{e['stepId']}" for e in dossier
        if (e["sugyaId"], e["stepId"]) not in by_key
    ]
    if missing:
        sys.exit("ERROR: no classification for: " + ", ".join(missing))

    extra = set(by_key) - {(e["sugyaId"], e["stepId"]) for e in dossier}
    if extra:
        sys.exit("ERROR: classification entries with no matching dossier case: "
                  + ", ".join(f"{s}/{st}" for s, st in extra))

    bad_class = [
        f"{k[0]}/{k[1]} -> {v['classification']!r}" for k, v in by_key.items()
        if v["classification"] not in VALID_CLASSES
    ]
    if bad_class:
        sys.exit("ERROR: invalid classification value(s): " + ", ".join(bad_class))

    merged = []
    for e in dossier:
        c = by_key[(e["sugyaId"], e["stepId"])]
        merged.append({
            "daf": e["daf"],
            "sugyaId": e["sugyaId"],
            "stepId": e["stepId"],
            "stepIndex": e["stepIndex"],
            "stepType": e["stepType"],
            "stepLabel": e["stepLabel"],
            "stepText": e["stepText"],
            "defectClass": e["defectClass"],
            "flaggedRef": e["flaggedRef"],
            "candidateIds": e["candidateIds"],
            "priorReviewIdx": e["priorReviewIdx"],
            "priorReviewReason": e["priorReviewReason"],
            "classification": c["classification"],
            "confidence": c["confidence"],
            "evidence": c["evidence"],
            "proposedAction": c["proposedAction"],
            "residualUncertainty": c["residualUncertainty"],
        })

    counts = Counter(m["classification"] for m in merged)

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    (DATA_DIR / "sourcerefs-blocker-table.json").write_text(
        json.dumps({"total": len(merged), "byClass": dict(counts), "cases": merged},
                   indent=2, ensure_ascii=False),
        encoding="utf-8")

    lines = []
    lines.append("# sourceRefs 33-case blocker table")
    lines.append("")
    lines.append("Generated by `modules/yoma/scripts/generate_sourcerefs_blocker_table.py` "
                 "from `docs/reports/data/sourcerefs-blocker-dossier.json` (mechanical evidence) "
                 "and `docs/reports/sourcerefs-blocker-classifications.json` (hand-authored "
                 "judgment). Regenerate after editing either input. This table does not itself "
                 "change any corpus file.")
    lines.append("")
    lines.append(f"**{len(merged)} cases total.**")
    for cls in ("QUALIFIED_CROSS_DAF", "ABSENT_OR_UNANCHORED", "TIED_CANDIDATES",
                "REPAIRABLE_LOCAL", "METADATA_ONLY"):
        lines.append(f"- `{cls}`: {counts.get(cls, 0)}")
    lines.append("")
    lines.append("| daf | sugya | step | defect class | classification | proposed action |")
    lines.append("|---|---|---|---|---|---|")
    for m in merged:
        action = m["proposedAction"].split(".")[0] + "."
        lines.append(
            f"| {m['daf']} | {m['sugyaId']} | {m['stepId']} | {m['defectClass']} | "
            f"**{m['classification']}** | {action} |"
        )
    lines.append("")
    lines.append("## Full evidence per case")
    lines.append("")
    for m in merged:
        lines.append(f"### {m['daf']} / {m['sugyaId']} / {m['stepId']} "
                      f"({m['classification']})")
        lines.append("")
        lines.append(f"- **Step type/label**: {m['stepType']} - {m['stepLabel']}")
        lines.append(f"- **Step text**: {m['stepText']}")
        lines.append(f"- **Defect class**: {m['defectClass']}")
        lines.append(f"- **Flagged ref**: `{json.dumps(m['flaggedRef'], ensure_ascii=False)}`")
        lines.append(f"- **Candidates considered**: {m['candidateIds'] or '(none - geometry-only conflict)'}")
        lines.append(f"- **Evidence**: {m['evidence']}")
        lines.append(f"- **Proposed action**: {m['proposedAction']}")
        lines.append(f"- **Residual uncertainty**: {m['residualUncertainty']}")
        lines.append("")

    (REPO / "docs" / "reports" / "sourcerefs-blocker-table.md").write_text(
        "\n".join(lines) + "\n", encoding="utf-8")

    print(f"{len(merged)} cases merged: {dict(counts)}")
    print(f"Wrote {DATA_DIR / 'sourcerefs-blocker-table.json'}")
    print(f"Wrote {REPO / 'docs' / 'reports' / 'sourcerefs-blocker-table.md'}")


if __name__ == "__main__":
    main()
